name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        run: |
          npm run build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          PUBLIC_CLIENT_ID: ${{ secrets.PUBLIC_CLIENT_ID }}
          PUBLIC_CLIENT_SECRET: ${{ secrets.PUBLIC_CLIENT_SECRET }}
          PUBLIC_DEV_API: ${{ secrets.DEV_API }}
          PUBLIC_PROD_API: ${{ secrets.PROD_API }}
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4